### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by 37385** [konohairoha/SweetMagic#2]
### there are some errors while building this mod

> home/runner/work/SweetMagicCustomized/SweetMagicCustomized/src/main/java/sweetmagic/worldgen/dungen/map/MapGenCastle.java:114: error: cannot find symbol
	                    	Block upBlock = this.getBlock(world, pos.up());
	                    	                    ^
  symbol: method getBlock(World,BlockPos)
/home/runner/work/SweetMagicCustomized/SweetMagicCustomized/src/main/java/sweetmagic/worldgen/dungen/map/MapGenCastle.java:119: error: cannot find symbol
									this.setAir(world, pos.up());
									    ^
  symbol: method setAir(World,BlockPos)
/home/runner/work/SweetMagicCustomized/SweetMagicCustomized/src/main/java/sweetmagic/worldgen/dungen/map/MapGenCastle.java:125: error: cannot find symbol
								this.setAir(world, pos.up());
								    ^
  symbol: method setAir(World,BlockPos)
/home/runner/work/SweetMagicCustomized/SweetMagicCustomized/src/main/java/sweetmagic/worldgen/dungen/map/MapGenCastle.java:130: error: cannot find symbol
								this.setAir(world, pos.up());
								    ^
  symbol: method setAir(World,BlockPos)
/home/runner/work/SweetMagicCustomized/SweetMagicCustomized/src/main/java/sweetmagic/worldgen/dungen/map/MapGenCastle.java:135: error: cannot find symbol
								this.setAir(world, pos.up());
								    ^
  symbol: method setAir(World,BlockPos)
/home/runner/work/SweetMagicCustomized/SweetMagicCustomized/src/main/java/sweetmagic/worldgen/dungen/map/MapGenCastle.java:146: error: cannot find symbol
	                    	if (this.getBlock(world, pos.up()) != Blocks.BONE_BLOCK) {
	                    	        ^
  symbol: method getBlock(World,BlockPos)
/home/runner/work/SweetMagicCustomized/SweetMagicCustomized/src/main/java/sweetmagic/worldgen/dungen/map/MapGenCastle.java:151: error: cannot find symbol
								this.setAir(world, pos.up());
								    ^
  symbol: method setAir(World,BlockPos)
/home/runner/work/SweetMagicCustomized/SweetMagicCustomized/src/main/java/sweetmagic/worldgen/dungen/map/MapGenCastle.java:164: error: cannot find symbol
		                    Block underBlock = this.getBlock(world, pos.down());
		                                           ^
  symbol: method getBlock(World,BlockPos)
/home/runner/work/SweetMagicCustomized/SweetMagicCustomized/src/main/java/sweetmagic/init/tile/magic/TileMFChanger.java:60: error: cannot find symbol
			if (stack.isEmpty() || !SlotPredicates.isMFItem(stack)) { continue; }
			                                      ^
  symbol:   method isMFItem(ItemStack)
  location: class SlotPredicates
/home/runner/work/SweetMagicCustomized/SweetMagicCustomized/src/main/java/sweetmagic/init/tile/magic/TileMFFurnace.java:269: error: cannot find symbol
		return SlotPredicates.isMFItem(stack);
		                     ^
  symbol:   method isMFItem(ItemStack)
  location: class SlotPredicates
/home/runner/work/SweetMagicCustomized/SweetMagicCustomized/src/main/java/sweetmagic/init/tile/magic/TileAetherFurnace.java:62: error: cannot find symbol
			if (stack.isEmpty() || !SlotPredicates.isMFItem(stack)) { continue; }
			                                      ^
  symbol:   method isMFItem(ItemStack)
  location: class SlotPredicates
/home/runner/work/SweetMagicCustomized/SweetMagicCustomized/src/main/java/sweetmagic/init/tile/container/ContainerMFArcaneTable.java:27: error: cannot find symbol
			this.addSlotToContainer(new ValidatedSlot(this.tile.getWand(), i, 39, 18 + i * 36, SlotPredicates.ISITEM));
			                                                                                                 ^
  symbol:   variable ISITEM
  location: class SlotPredicates
/home/runner/work/SweetMagicCustomized/SweetMagicCustomized/src/main/java/sweetmagic/init/item/sm/accessorie/SMAcce.java:226: error: cannot find symbol
				if (ItemHelper.hasSpace(player.inventory.mainInventory, item.getItem())) {
				              ^
  symbol:   method hasSpace(NonNullList<ItemStack>,ItemStack)
  location: class ItemHelper
/home/runner/work/SweetMagicCustomized/SweetMagicCustomized/src/main/java/sweetmagic/init/item/sm/accessorie/SMAcce.java:227: error: cannot find symbol
					WorldHelper.gravitateEntityTowards(item, player.posX, player.posY, player.posZ);
					           ^
  symbol:   method gravitateEntityTowards(EntityItem,double,double,double)
  location: class WorldHelper
/home/runner/work/SweetMagicCustomized/SweetMagicCustomized/src/main/java/sweetmagic/init/item/sm/accessorie/SMAcce.java:236: error: cannot find symbol
				WorldHelper.gravitateEntityTowards(xpOrb, player.posX, player.posY, player.posZ);
				           ^
  symbol:   method gravitateEntityTowards(EntityXPOrb,double,double,double)
  location: class WorldHelper

It seems that some code is not upload );

**Comment by konohairoha** [comment]
I forgot to upload some of the sources.
Thanks for the report.

By the way, were you trying to test something with my source code?

**Comment by 37385** [comment]
In some of the modpack,This mod's magic is a little weak,and i try to add a config that can set the max enchant level of ''Wand Add Power''
By the way ,could you add a config about the magic attack damage?

**Comment by konohairoha** [comment]
You want to be able to raise the enchantment level of ''Wand Add Power'' to more than 10, right?
I'll also add a setting regarding the damage of magic attacks.
I'll deal with both of them in the next update.

**Comment by 37385** [comment]
> You want to be able to raise the enchantment level of ''Wand Add Power'' to more than 10, right?
> I'll also add a setting regarding the damage of magic attacks.
> I'll deal with both of them in the next update.

YES
THANKS
