### ISSUE TITLE
Fascinated Fairy Crashes Client

### ISSUE THREAD

**Issue by Lingqm1234** [konohairoha/SweetMagic#5]
I used this mod in a server. It is version 1.2.1. When I encountered this boss, my client crashed, the server is OK.
Since I'm still at the same place when I connect to the server, it stops me from playing anymore.
Hope you may see it.
Other mods are: Journey map, hwyla, jei, Just Another Rotten Flesh to Leather Mod(I didn't know this mod can convert rotten flesh to leather too) and custom skin loader.
[crash-2021-08-14_16.53.25-client.txt](https://github.com/konohairoha/SweetMagic/files/6986192/crash-2021-08-14_16.53.25-client.txt)
(I don't have a Twitch account and it is extremely difficult to get one because I'm from China. So I have to post it here.)

**Comment by konohairoha** [comment]
Thanks for the report.
It is indeed a serious bug.
I will provide you with a fixed file so you can check it out.
Please let me know if you find any more bugs.
The file I gave you is still under development, so please share it only with people who are playing on that server.
[SweetMagic-1.2.2-beta1-alpha6.zip](https://github.com/konohairoha/SweetMagic/files/6986745/SweetMagic-1.2.2-beta1-alpha6.zip)

**Comment by Lingqm1234** [comment]
Thanks! If I see any more bugs, I'll open another issue. I'll close it now.
